image: node:8.5.0

cache:
  paths:
  - node_modules/

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - build
  only:
    - master