export const GET_QUESTIONS_REQUEST = 'GET_QUESTION_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTIONS_FAILED = 'GET_QUESTION_FAILED';
export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAILED = 'ADD_QUESTION_FAILED';